### PR TITLE
Update readme and repo for upcoming Spring 2018 workshop [WIP]

### PR DESCRIPTION
**Pull request by dcwalk**
Things:

- [x] update readme title
- [x] add link to tomesh and TPL workshop listing
- [ ] update repo name (now that we have one?)
- [x] links to modules from readme
- [x] clean up/make consistent formatting (improved! But not perfect)

### CODE REVIEW

**Comment by dcwalk** [comment]
hey all, did some linking and knitting together of repo formatting.

Could we rename this repo to something in line with the workshop name?
`peer-to-peer-internet-workshop`
`peer-to-peer-workshop`
`p2p-internet-workshop`

**Comment by benhylau** [comment]
I like `peer-to-peer-internet-workshop`, also fine with `p2p-internet-workshop`

**Comment by benhylau** [comment]
@dcwalk can we merge this?

**Comment by dcwalk** [comment]
Yeah, I was just waiting to give space for others to take a look. Merging in

**Pull request merged**
